name: PR Checks
run-name: ${{ github.actor }} is testing prs.
on:
  pull_request:
    branches: [ master ]
jobs:
  PR-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Run linting
        uses: golangci/golangci-lint-action@v3
      - name: Run testing
        run: go test -v ./...
